In [34]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio

In [2]:
LOG_DIR = "../logs/"

AGG_LOG = "he-aggregation-service"
CLIENT1_LOG = "he-client-1-go"
CLIENT2_LOG = "he-client-2-go"

In [3]:
agg_time = pd.read_csv(f"{LOG_DIR}{AGG_LOG}-time.csv")
client1_time = pd.read_csv(f"{LOG_DIR}{CLIENT1_LOG}-time.csv")
client2_time = pd.read_csv(f"{LOG_DIR}{CLIENT2_LOG}-time.csv")

agg_time["Service"] = "AggregationService"
client1_time["Service"] = "Client1"
client2_time["Service"] = "Client2"

client1_time.head()

,Date,EndTime,Name,Runtime,Service
0,2025/07/22,14:41:25.975143,DataSpaceClientService - RegisterClient,13.205041ms,Client1
1,2025/07/22,14:41:25.983500,HEService - SetParameters,8.294416ms,Client1
2,2025/07/22,14:41:30.996970,HEService - PartialShareAggregation,8.583µs,Client1
3,2025/07/22,14:41:31.011173,EncryptionHandler - handleReceivePublicKey,1.149375ms,Client1
4,2025/07/22,14:41:31.037810,HEService - PartialRelinKeyAggregation,2.379958ms,Client1

In [20]:
data_joined = pd.concat(
    [agg_time, client1_time, client2_time],
    axis=0)

data_joined = data_joined.reset_index(drop=True)

data_joined

,Date,EndTime,Name,Runtime,Service
0,2025/07/22,14:41:25.964356,addClient,1.833µs,AggregationService
1,2025/07/22,14:41:31.197952,startEncryptionSetupPhaseFor,5.233553417s,AggregationService
2,2025/07/22,14:41:34.049860,addClient,833ns,AggregationService
3,2025/07/22,14:41:39.414548,startEncryptionSetupPhaseFor,5.36460525s,AggregationService
4,2025/07/22,14:41:53.083988,requestClientTraining,4.722084ms,AggregationService
5,2025/07/22,14:42:24.106563,aggregateWeights,49.423458ms,AggregationService
6,2025/07/22,14:42:24.485907,initiateKeySwitchGeneration,379.262666ms,AggregationService
7,2025/07/22,14:42:27.629453,updateClientModels,2.239003917s,AggregationService
8,2025/07/22,14:42:32.191933,requestClientTraining,3.158125ms,AggregationService
9,2025/07/22,14:42:51.979431,requestClientTraining,1.941917ms,AggregationService
10,2025/07/22,14:42:54.093164,aggregateWeights,53.153583ms,AggregationService
11,2025/07/22,14:42:54.468503,initiateKeySwitchGeneration,375.210542ms,AggregationService
12,2025/07/22,14:42:57.712434,updateClientModels,2.278980625s,AggregationService
13,2025/07/22,14:43:24.133487,aggregateWeights,56.027542ms,AggregationService
14,2025/07/22,14:43:24.514961,initiateKeySwitchGeneration,381.408ms,AggregationService
15,2025/07/22,14:43:27.626251,updateClientModels,2.193520333s,AggregationService
16,2025/07/22,14:41:25.975143,DataSpaceClientService - RegisterClient,13.205041ms,Client1
17,2025/07/22,14:41:25.983500,HEService - SetParameters,8.294416ms,Client1
18,2025/07/22,14:41:30.996970,HEService - PartialShareAggregation,8.583µs,Client1
19,2025/07/22,14:41:31.011173,EncryptionHandler - handleReceivePublicKey,1.149375ms,Client1
20,2025/07/22,14:41:31.037810,HEService - PartialRelinKeyAggregation,2.379958ms,Client1
21,2025/07/22,14:41:39.057244,HEService - PartialShareAggregation,2.375µs,Client1
22,2025/07/22,14:41:39.062853,EncryptionHandler - handleReceivePublicKey,1.256417ms,Client1
23,2025/07/22,14:41:39.082244,HEService - PartialRelinKeyAggregation,2.257125ms,Client1
24,2025/07/22,14:42:05.271684,HEService - Encrypt,861.965792ms,Client1
25,2025/07/22,14:42:06.613421,DataSpaceClientService - UploadData,1.30605325s,Client1
26,2025/07/22,14:42:24.294186,HEService - PublicKeySwitchGeneration,29.733375ms,Client1
27,2025/07/22,14:42:24.294211,EncryptionHandler - handlePublicKeySwitch,106.144666ms,Client1
28,2025/07/22,14:42:24.487010,EncryptionHandler - handlePublicKeySwitchAggre...,5.791µs,Client1
29,2025/07/22,14:42:44.415670,HEService - Encrypt,845.833792ms,Client1
30,2025/07/22,14:42:45.530398,DataSpaceClientService - UploadData,1.087493542s,Client1
31,2025/07/22,14:42:54.275508,HEService - PublicKeySwitchGeneration,29.595625ms,Client1
32,2025/07/22,14:42:54.275537,EncryptionHandler - handlePublicKeySwitch,99.497791ms,Client1
33,2025/07/22,14:42:54.469691,EncryptionHandler - handlePublicKeySwitchAggre...,6.792µs,Client1
34,2025/07/22,14:43:04.942781,HEService - Encrypt,859.017542ms,Client1
35,2025/07/22,14:43:06.080628,DataSpaceClientService - UploadData,1.107080583s,Client1
36,2025/07/22,14:43:24.514684,HEService - PublicKeySwitchGeneration,28.44125ms,Client1
37,2025/07/22,14:43:24.514714,EncryptionHandler - handlePublicKeySwitch,162.235125ms,Client1
38,2025/07/22,14:43:24.515568,EncryptionHandler - handlePublicKeySwitchAggre...,6.75µs,Client1
39,2025/07/22,14:41:34.060062,DataSpaceClientService - RegisterClient,12.486834ms,Client2
40,2025/07/22,14:41:34.068452,HEService - SetParameters,8.336709ms,Client2
41,2025/07/22,14:41:39.058305,HEService - PartialShareAggregation,1.5µs,Client2
42,2025/07/22,14:41:39.064792,EncryptionHandler - handleReceivePublicKey,1.117458ms,Client2
43,2025/07/22,14:41:39.259197,HEService - PartialRelinKeyAggregation,2.449458ms,Client2
44,2025/07/22,14:42:05.300475,HEService - Encrypt,864.07375ms,Client2
45,2025/07/22,14:42:06.638348,DataSpaceClientService - UploadData,1.300053334s,Client2
46,2025/07/22,14:42:24.485745,HEService - PublicKeySwitchGeneration,29.365167ms,Client2
47,2025/07/22,14:42:24.485772,EncryptionHandler - handlePublicKeySwitch,104.59125ms,Client2
48,2025/07/22,14:42:24.486488,EncryptionHandler - handlePublicKeySwitchAggre...,6.625µs,Client2
49,2025/07/22,14:42:44.537027,HEService - Encrypt,854.644792ms,Client2
50,2025/07/22,14:42:45.700854,DataSpaceClientService - UploadData,1.128156083s,Client2
51,2025/07/22,14:42:54.468298,HEService - PublicKeySwitchGeneration,29.828959ms,Client2
52,2025/07/22,14:42:54.468348,EncryptionHandler - handlePublicKeySwitch,139.099875ms,Client2
53,2025/07/22,14:42:54.469092,EncryptionHandler - handlePublicKeySwitchAggre...,8.083µs,Client2
54,2025/07/22,14:43:04.951598,HEService - Encrypt,853.023042ms,Client2
55,2025/07/22,14:43:06.081617,DataSpaceClientService - UploadData,1.097052s,Client2
56,2025/07/22,14:43:24.298135,HEService - PublicKeySwitchGeneration,29.707083ms,Client2
57,2025/07/22,14:43:24.298161,EncryptionHandler - handlePublicKeySwitch,128.162417ms,Client2
58,2025/07/22,14:43:24.516097,EncryptionHandler - handlePublicKeySwitchAggre...,5.167µs,Client2

In [21]:
def parse_duration_to_ms(time_str):
    """Parse milliseconds, microseconds, nanoseconds or seconds from a string."""
    if "ms" in time_str:
        return float(time_str.replace("ms", "").strip())
    elif "us" in time_str:
        return float(time_str.replace("us", "").strip()) / 1000.0
    elif "µs" in time_str:
        return float(time_str.replace("µs", "").strip()) / 1000.0
    elif "ns" in time_str:
        return float(time_str.replace("ns", "").strip()) / 1_000_000.0
    elif "s" in time_str:
        return float(time_str.replace("s", "").strip()) * 1000.0
    else:
        raise ValueError(f"Unknown time format: {time_str}")


def create_timeline_offset(df):
    """Create a timeline with an offset for the x-axis."""
    min_time = df["EndTime"].min()
    df["StartMs"] = (pd.to_datetime(df["EndTime"], format="%H:%M:%S.%f") - pd.to_datetime(min_time, format="%H:%M:%S.%f")).dt.total_seconds() * 1000
    
    return df
    
#agg_time["runtime_ms"] = agg_time["Runtime"].apply(parse_duration_to_ms)
#client1_time["runtime_ms"] = client1_time["Runtime"].apply(parse_duration_to_ms)
#client2_time["runtime_ms"] = client2_time["Runtime"].apply(parse_duration_to_ms)
data_joined["runtime_ms"] = data_joined["Runtime"].apply(parse_duration_to_ms)

#agg_time = create_timeline_offset(agg_time)
#client1_time = create_timeline_offset(client1_time)
#client2_time = create_timeline_offset(client2_time)
data_joined = create_timeline_offset(data_joined)

data_joined["EndMs"] = data_joined["StartMs"] + data_joined["runtime_ms"]

data_joined = data_joined.sort_values(by=["StartMs", "EndMs"])
data_joined.reset_index(drop=True, inplace=True)
data_joined

,Date,EndTime,Name,Runtime,Service,runtime_ms,StartMs,EndMs
0,2025/07/22,14:41:25.964356,addClient,1.833µs,AggregationService,0.001833,0.000,0.001833
1,2025/07/22,14:41:25.975143,DataSpaceClientService - RegisterClient,13.205041ms,Client1,13.205041,10.787,23.992041
2,2025/07/22,14:41:25.983500,HEService - SetParameters,8.294416ms,Client1,8.294416,19.144,27.438416
3,2025/07/22,14:41:30.996970,HEService - PartialShareAggregation,8.583µs,Client1,0.008583,5032.614,5032.622583
4,2025/07/22,14:41:31.011173,EncryptionHandler - handleReceivePublicKey,1.149375ms,Client1,1.149375,5046.817,5047.966375
5,2025/07/22,14:41:31.037810,HEService - PartialRelinKeyAggregation,2.379958ms,Client1,2.379958,5073.454,5075.833958
6,2025/07/22,14:41:31.197952,startEncryptionSetupPhaseFor,5.233553417s,AggregationService,5233.553417,5233.596,10467.149417
7,2025/07/22,14:41:34.049860,addClient,833ns,AggregationService,0.000833,8085.504,8085.504833
8,2025/07/22,14:41:34.060062,DataSpaceClientService - RegisterClient,12.486834ms,Client2,12.486834,8095.706,8108.192834
9,2025/07/22,14:41:34.068452,HEService - SetParameters,8.336709ms,Client2,8.336709,8104.096,8112.432709
10,2025/07/22,14:41:39.057244,HEService - PartialShareAggregation,2.375µs,Client1,0.002375,13092.888,13092.890375
11,2025/07/22,14:41:39.058305,HEService - PartialShareAggregation,1.5µs,Client2,0.001500,13093.949,13093.950500
12,2025/07/22,14:41:39.062853,EncryptionHandler - handleReceivePublicKey,1.256417ms,Client1,1.256417,13098.497,13099.753417
13,2025/07/22,14:41:39.064792,EncryptionHandler - handleReceivePublicKey,1.117458ms,Client2,1.117458,13100.436,13101.553458
14,2025/07/22,14:41:39.082244,HEService - PartialRelinKeyAggregation,2.257125ms,Client1,2.257125,13117.888,13120.145125
15,2025/07/22,14:41:39.259197,HEService - PartialRelinKeyAggregation,2.449458ms,Client2,2.449458,13294.841,13297.290458
16,2025/07/22,14:41:39.414548,startEncryptionSetupPhaseFor,5.36460525s,AggregationService,5364.605250,13450.192,18814.797250
17,2025/07/22,14:41:53.083988,requestClientTraining,4.722084ms,AggregationService,4.722084,27119.632,27124.354084
18,2025/07/22,14:42:05.271684,HEService - Encrypt,861.965792ms,Client1,861.965792,39307.328,40169.293792
19,2025/07/22,14:42:05.300475,HEService - Encrypt,864.07375ms,Client2,864.073750,39336.119,40200.192750
20,2025/07/22,14:42:06.613421,DataSpaceClientService - UploadData,1.30605325s,Client1,1306.053250,40649.065,41955.118250
21,2025/07/22,14:42:06.638348,DataSpaceClientService - UploadData,1.300053334s,Client2,1300.053334,40673.992,41974.045334
22,2025/07/22,14:42:24.106563,aggregateWeights,49.423458ms,AggregationService,49.423458,58142.207,58191.630458
23,2025/07/22,14:42:24.294186,HEService - PublicKeySwitchGeneration,29.733375ms,Client1,29.733375,58329.830,58359.563375
24,2025/07/22,14:42:24.294211,EncryptionHandler - handlePublicKeySwitch,106.144666ms,Client1,106.144666,58329.855,58435.999666
25,2025/07/22,14:42:24.485745,HEService - PublicKeySwitchGeneration,29.365167ms,Client2,29.365167,58521.389,58550.754167
26,2025/07/22,14:42:24.485772,EncryptionHandler - handlePublicKeySwitch,104.59125ms,Client2,104.591250,58521.416,58626.007250
27,2025/07/22,14:42:24.485907,initiateKeySwitchGeneration,379.262666ms,AggregationService,379.262666,58521.551,58900.813666
28,2025/07/22,14:42:24.486488,EncryptionHandler - handlePublicKeySwitchAggre...,6.625µs,Client2,0.006625,58522.132,58522.138625
29,2025/07/22,14:42:24.487010,EncryptionHandler - handlePublicKeySwitchAggre...,5.791µs,Client1,0.005791,58522.654,58522.659791
30,2025/07/22,14:42:27.629453,updateClientModels,2.239003917s,AggregationService,2239.003917,61665.097,63904.100917
31,2025/07/22,14:42:32.191933,requestClientTraining,3.158125ms,AggregationService,3.158125,66227.577,66230.735125
32,2025/07/22,14:42:44.415670,HEService - Encrypt,845.833792ms,Client1,845.833792,78451.314,79297.147792
33,2025/07/22,14:42:44.537027,HEService - Encrypt,854.644792ms,Client2,854.644792,78572.671,79427.315792
34,2025/07/22,14:42:45.530398,DataSpaceClientService - UploadData,1.087493542s,Client1,1087.493542,79566.042,80653.535542
35,2025/07/22,14:42:45.700854,DataSpaceClientService - UploadData,1.128156083s,Client2,1128.156083,79736.498,80864.654083
36,2025/07/22,14:42:51.979431,requestClientTraining,1.941917ms,AggregationService,1.941917,86015.075,86017.016917
37,2025/07/22,14:42:54.093164,aggregateWeights,53.153583ms,AggregationService,53.153583,88128.808,88181.961583
38,2025/07/22,14:42:54.275508,HEService - PublicKeySwitchGeneration,29.595625ms,Client1,29.595625,88311.152,88340.747625
39,2025/07/22,14:42:54.275537,EncryptionHandler - handlePublicKeySwitch,99.497791ms,Client1,99.497791,88311.181,88410.678791
40,2025/07/22,14:42:54.468298,HEService - PublicKeySwitchGeneration,29.828959ms,Client2,29.828959,88503.942,88533.770959
41,2025/07/22,14:42:54.468348,EncryptionHandler - handlePublicKeySwitch,139.099875ms,Client2,139.099875,88503.992,88643.091875
42,2025/07/22,14:42:54.468503,initiateKeySwitchGeneration,375.210542ms,AggregationService,375.210542,88504.147,88879.357542
43,2025/07/22,14:42:54.469092,EncryptionHandler - handlePublicKeySwitchAggre...,8.083µs,Client2,0.008083,88504.736,88504.744083
44,2025/07/22,14:42:54.469691,EncryptionHandler - handlePublicKeySwitchAggre...,6.792µs,Client1,0.006792,88505.335,88505.341792
45,2025/07/22,14:42:57.712434,updateClientModels,2.278980625s,AggregationService,2278.980625,91748.078,94027.058625
46,2025/07/22,14:43:04.942781,HEService - Encrypt,859.017542ms,Client1,859.017542,98978.425,99837.442542
47,2025/07/22,14:43:04.951598,HEService - Encrypt,853.023042ms,Client2,853.023042,98987.242,99840.265042
48,2025/07/22,14:43:06.080628,DataSpaceClientService - UploadData,1.107080583s,Client1,1107.080583,100116.272,101223.352583
49,2025/07/22,14:43:06.081617,DataSpaceClientService - UploadData,1.097052s,Client2,1097.052000,100117.261,101214.313000
50,2025/07/22,14:43:24.133487,aggregateWeights,56.027542ms,AggregationService,56.027542,118169.131,118225.158542
51,2025/07/22,14:43:24.298135,HEService - PublicKeySwitchGeneration,29.707083ms,Client2,29.707083,118333.779,118363.486083
52,2025/07/22,14:43:24.298161,EncryptionHandler - handlePublicKeySwitch,128.162417ms,Client2,128.162417,118333.805,118461.967417
53,2025/07/22,14:43:24.514684,HEService - PublicKeySwitchGeneration,28.44125ms,Client1,28.441250,118550.328,118578.769250
54,2025/07/22,14:43:24.514714,EncryptionHandler - handlePublicKeySwitch,162.235125ms,Client1,162.235125,118550.358,118712.593125
55,2025/07/22,14:43:24.514961,initiateKeySwitchGeneration,381.408ms,AggregationService,381.408000,118550.605,118932.013000
56,2025/07/22,14:43:24.515568,EncryptionHandler - handlePublicKeySwitchAggre...,6.75µs,Client1,0.006750,118551.212,118551.218750
57,2025/07/22,14:43:24.516097,EncryptionHandler - handlePublicKeySwitchAggre...,5.167µs,Client2,0.005167,118551.741,118551.746167
58,2025/07/22,14:43:27.626251,updateClientModels,2.193520333s,AggregationService,2193.520333,121661.895,123855.415333

In [81]:
print(pio.templates)

pio.templates["research"] = go.layout.Template(
    layout=dict(
        font=dict(color="#000000"),
        paper_bgcolor="#ffffff",
        plot_bgcolor="#ffffff",
        hovermode="closest",
        xaxis=dict(
            tickangle=-45,
            showline=True,
            linewidth=1,
            linecolor="#373737",
            ticks="inside",
            showgrid=True,
            gridcolor="#373737",
            zeroline=True,
            zerolinecolor="#373737",
            zerolinewidth=1,
            mirror=True
        ),
        yaxis=dict(
            showline=True,
            linewidth=1,
            linecolor="#373737",
            ticks="inside",
            showgrid=True,
            gridcolor="#373737",
            zeroline=True,
            zerolinecolor="#373737",
            zerolinewidth=1,
            mirror=True
        )
    )
)

pio.templates.default = "plotly_white+research"

Templates configuration
-----------------------
    Default template: 'plotly_white+research'
    Available templates:
        ['ggplot2', 'seaborn', 'simple_white', 'plotly',
         'plotly_white', 'plotly_dark', 'presentation', 'xgridoff',
         'ygridoff', 'gridon', 'none', 'research']

In [82]:
import plotly.express as px
import plotly.graph_objects as go


df = px.data.tips()
fig = px.bar(data_joined[data_joined["runtime_ms"] >= 100], base="StartMs", x="runtime_ms", y="Service", color='Name', orientation='h',
             hover_data=["EndTime", "StartMs", "runtime_ms"], color_discrete_sequence=px.colors.qualitative.Safe,
             height=400)
fig.show()

In [83]:
# remove all waiting times

data_joined.at[data_joined.index[0], "Start_without_offset"] = data_joined.at[data_joined.index[0], "StartMs"]
data_joined.at[data_joined.index[0], "End_without_offset"] = data_joined.at[data_joined.index[0], "EndMs"]

for i in range(1, len(data_joined)):
    data_joined.at[data_joined.index[i], "Start_without_offset"] = data_joined.iloc[i-1]["End_without_offset"]
    data_joined.at[data_joined.index[i], "End_without_offset"] = data_joined.at[data_joined.index[i], "Start_without_offset"] + data_joined.at[data_joined.index[i], "runtime_ms"]
data_joined

,Date,EndTime,Name,Runtime,Service,runtime_ms,StartMs,EndMs,Start_without_offset,End_without_offset
0,2025/07/22,14:41:25.964356,addClient,1.833µs,AggregationService,0.001833,0.000,0.001833,0.000000,0.001833
1,2025/07/22,14:41:25.975143,DataSpaceClientService - RegisterClient,13.205041ms,Client1,13.205041,10.787,23.992041,0.001833,13.206874
2,2025/07/22,14:41:25.983500,HEService - SetParameters,8.294416ms,Client1,8.294416,19.144,27.438416,13.206874,21.501290
3,2025/07/22,14:41:30.996970,HEService - PartialShareAggregation,8.583µs,Client1,0.008583,5032.614,5032.622583,21.501290,21.509873
4,2025/07/22,14:41:31.011173,EncryptionHandler - handleReceivePublicKey,1.149375ms,Client1,1.149375,5046.817,5047.966375,21.509873,22.659248
5,2025/07/22,14:41:31.037810,HEService - PartialRelinKeyAggregation,2.379958ms,Client1,2.379958,5073.454,5075.833958,22.659248,25.039206
6,2025/07/22,14:41:31.197952,startEncryptionSetupPhaseFor,5.233553417s,AggregationService,5233.553417,5233.596,10467.149417,25.039206,5258.592623
7,2025/07/22,14:41:34.049860,addClient,833ns,AggregationService,0.000833,8085.504,8085.504833,5258.592623,5258.593456
8,2025/07/22,14:41:34.060062,DataSpaceClientService - RegisterClient,12.486834ms,Client2,12.486834,8095.706,8108.192834,5258.593456,5271.080290
9,2025/07/22,14:41:34.068452,HEService - SetParameters,8.336709ms,Client2,8.336709,8104.096,8112.432709,5271.080290,5279.416999
10,2025/07/22,14:41:39.057244,HEService - PartialShareAggregation,2.375µs,Client1,0.002375,13092.888,13092.890375,5279.416999,5279.419374
11,2025/07/22,14:41:39.058305,HEService - PartialShareAggregation,1.5µs,Client2,0.001500,13093.949,13093.950500,5279.419374,5279.420874
12,2025/07/22,14:41:39.062853,EncryptionHandler - handleReceivePublicKey,1.256417ms,Client1,1.256417,13098.497,13099.753417,5279.420874,5280.677291
13,2025/07/22,14:41:39.064792,EncryptionHandler - handleReceivePublicKey,1.117458ms,Client2,1.117458,13100.436,13101.553458,5280.677291,5281.794749
14,2025/07/22,14:41:39.082244,HEService - PartialRelinKeyAggregation,2.257125ms,Client1,2.257125,13117.888,13120.145125,5281.794749,5284.051874
15,2025/07/22,14:41:39.259197,HEService - PartialRelinKeyAggregation,2.449458ms,Client2,2.449458,13294.841,13297.290458,5284.051874,5286.501332
16,2025/07/22,14:41:39.414548,startEncryptionSetupPhaseFor,5.36460525s,AggregationService,5364.605250,13450.192,18814.797250,5286.501332,10651.106582
17,2025/07/22,14:41:53.083988,requestClientTraining,4.722084ms,AggregationService,4.722084,27119.632,27124.354084,10651.106582,10655.828666
18,2025/07/22,14:42:05.271684,HEService - Encrypt,861.965792ms,Client1,861.965792,39307.328,40169.293792,10655.828666,11517.794458
19,2025/07/22,14:42:05.300475,HEService - Encrypt,864.07375ms,Client2,864.073750,39336.119,40200.192750,11517.794458,12381.868208
20,2025/07/22,14:42:06.613421,DataSpaceClientService - UploadData,1.30605325s,Client1,1306.053250,40649.065,41955.118250,12381.868208,13687.921458
21,2025/07/22,14:42:06.638348,DataSpaceClientService - UploadData,1.300053334s,Client2,1300.053334,40673.992,41974.045334,13687.921458,14987.974792
22,2025/07/22,14:42:24.106563,aggregateWeights,49.423458ms,AggregationService,49.423458,58142.207,58191.630458,14987.974792,15037.398250
23,2025/07/22,14:42:24.294186,HEService - PublicKeySwitchGeneration,29.733375ms,Client1,29.733375,58329.830,58359.563375,15037.398250,15067.131625
24,2025/07/22,14:42:24.294211,EncryptionHandler - handlePublicKeySwitch,106.144666ms,Client1,106.144666,58329.855,58435.999666,15067.131625,15173.276291
25,2025/07/22,14:42:24.485745,HEService - PublicKeySwitchGeneration,29.365167ms,Client2,29.365167,58521.389,58550.754167,15173.276291,15202.641458
26,2025/07/22,14:42:24.485772,EncryptionHandler - handlePublicKeySwitch,104.59125ms,Client2,104.591250,58521.416,58626.007250,15202.641458,15307.232708
27,2025/07/22,14:42:24.485907,initiateKeySwitchGeneration,379.262666ms,AggregationService,379.262666,58521.551,58900.813666,15307.232708,15686.495374
28,2025/07/22,14:42:24.486488,EncryptionHandler - handlePublicKeySwitchAggre...,6.625µs,Client2,0.006625,58522.132,58522.138625,15686.495374,15686.501999
29,2025/07/22,14:42:24.487010,EncryptionHandler - handlePublicKeySwitchAggre...,5.791µs,Client1,0.005791,58522.654,58522.659791,15686.501999,15686.507790
30,2025/07/22,14:42:27.629453,updateClientModels,2.239003917s,AggregationService,2239.003917,61665.097,63904.100917,15686.507790,17925.511707
31,2025/07/22,14:42:32.191933,requestClientTraining,3.158125ms,AggregationService,3.158125,66227.577,66230.735125,17925.511707,17928.669832
32,2025/07/22,14:42:44.415670,HEService - Encrypt,845.833792ms,Client1,845.833792,78451.314,79297.147792,17928.669832,18774.503624
33,2025/07/22,14:42:44.537027,HEService - Encrypt,854.644792ms,Client2,854.644792,78572.671,79427.315792,18774.503624,19629.148416
34,2025/07/22,14:42:45.530398,DataSpaceClientService - UploadData,1.087493542s,Client1,1087.493542,79566.042,80653.535542,19629.148416,20716.641958
35,2025/07/22,14:42:45.700854,DataSpaceClientService - UploadData,1.128156083s,Client2,1128.156083,79736.498,80864.654083,20716.641958,21844.798041
36,2025/07/22,14:42:51.979431,requestClientTraining,1.941917ms,AggregationService,1.941917,86015.075,86017.016917,21844.798041,21846.739958
37,2025/07/22,14:42:54.093164,aggregateWeights,53.153583ms,AggregationService,53.153583,88128.808,88181.961583,21846.739958,21899.893541
38,2025/07/22,14:42:54.275508,HEService - PublicKeySwitchGeneration,29.595625ms,Client1,29.595625,88311.152,88340.747625,21899.893541,21929.489166
39,2025/07/22,14:42:54.275537,EncryptionHandler - handlePublicKeySwitch,99.497791ms,Client1,99.497791,88311.181,88410.678791,21929.489166,22028.986957
40,2025/07/22,14:42:54.468298,HEService - PublicKeySwitchGeneration,29.828959ms,Client2,29.828959,88503.942,88533.770959,22028.986957,22058.815916
41,2025/07/22,14:42:54.468348,EncryptionHandler - handlePublicKeySwitch,139.099875ms,Client2,139.099875,88503.992,88643.091875,22058.815916,22197.915791
42,2025/07/22,14:42:54.468503,initiateKeySwitchGeneration,375.210542ms,AggregationService,375.210542,88504.147,88879.357542,22197.915791,22573.126333
43,2025/07/22,14:42:54.469092,EncryptionHandler - handlePublicKeySwitchAggre...,8.083µs,Client2,0.008083,88504.736,88504.744083,22573.126333,22573.134416
44,2025/07/22,14:42:54.469691,EncryptionHandler - handlePublicKeySwitchAggre...,6.792µs,Client1,0.006792,88505.335,88505.341792,22573.134416,22573.141208
45,2025/07/22,14:42:57.712434,updateClientModels,2.278980625s,AggregationService,2278.980625,91748.078,94027.058625,22573.141208,24852.121833
46,2025/07/22,14:43:04.942781,HEService - Encrypt,859.017542ms,Client1,859.017542,98978.425,99837.442542,24852.121833,25711.139375
47,2025/07/22,14:43:04.951598,HEService - Encrypt,853.023042ms,Client2,853.023042,98987.242,99840.265042,25711.139375,26564.162417
48,2025/07/22,14:43:06.080628,DataSpaceClientService - UploadData,1.107080583s,Client1,1107.080583,100116.272,101223.352583,26564.162417,27671.243000
49,2025/07/22,14:43:06.081617,DataSpaceClientService - UploadData,1.097052s,Client2,1097.052000,100117.261,101214.313000,27671.243000,28768.295000
50,2025/07/22,14:43:24.133487,aggregateWeights,56.027542ms,AggregationService,56.027542,118169.131,118225.158542,28768.295000,28824.322542
51,2025/07/22,14:43:24.298135,HEService - PublicKeySwitchGeneration,29.707083ms,Client2,29.707083,118333.779,118363.486083,28824.322542,28854.029625
52,2025/07/22,14:43:24.298161,EncryptionHandler - handlePublicKeySwitch,128.162417ms,Client2,128.162417,118333.805,118461.967417,28854.029625,28982.192042
53,2025/07/22,14:43:24.514684,HEService - PublicKeySwitchGeneration,28.44125ms,Client1,28.441250,118550.328,118578.769250,28982.192042,29010.633292
54,2025/07/22,14:43:24.514714,EncryptionHandler - handlePublicKeySwitch,162.235125ms,Client1,162.235125,118550.358,118712.593125,29010.633292,29172.868417
55,2025/07/22,14:43:24.514961,initiateKeySwitchGeneration,381.408ms,AggregationService,381.408000,118550.605,118932.013000,29172.868417,29554.276417
56,2025/07/22,14:43:24.515568,EncryptionHandler - handlePublicKeySwitchAggre...,6.75µs,Client1,0.006750,118551.212,118551.218750,29554.276417,29554.283167
57,2025/07/22,14:43:24.516097,EncryptionHandler - handlePublicKeySwitchAggre...,5.167µs,Client2,0.005167,118551.741,118551.746167,29554.283167,29554.288334
58,2025/07/22,14:43:27.626251,updateClientModels,2.193520333s,AggregationService,2193.520333,121661.895,123855.415333,29554.288334,31747.808667

In [84]:
df = px.data.tips()
fig = px.bar(data_joined, base="Start_without_offset", x="runtime_ms", y="Service", color='Name', orientation='h',
             hover_data=["EndTime", "StartMs", "runtime_ms"], color_discrete_sequence=px.colors.qualitative.Safe,
             height=400)
fig.show()

In [85]:
data_joined.reset_index(drop=True, inplace=True)

first_occ_encrypt = data_joined.loc[data_joined["Name"] == "requestClientTraining"].index[0]
print(first_occ_encrypt)

initializiation_data = data_joined[:first_occ_encrypt]
initializiation_data

17

,Date,EndTime,Name,Runtime,Service,runtime_ms,StartMs,EndMs,Start_without_offset,End_without_offset
0,2025/07/22,14:41:25.964356,addClient,1.833µs,AggregationService,0.001833,0.000,0.001833,0.000000,0.001833
1,2025/07/22,14:41:25.975143,DataSpaceClientService - RegisterClient,13.205041ms,Client1,13.205041,10.787,23.992041,0.001833,13.206874
2,2025/07/22,14:41:25.983500,HEService - SetParameters,8.294416ms,Client1,8.294416,19.144,27.438416,13.206874,21.501290
3,2025/07/22,14:41:30.996970,HEService - PartialShareAggregation,8.583µs,Client1,0.008583,5032.614,5032.622583,21.501290,21.509873
4,2025/07/22,14:41:31.011173,EncryptionHandler - handleReceivePublicKey,1.149375ms,Client1,1.149375,5046.817,5047.966375,21.509873,22.659248
5,2025/07/22,14:41:31.037810,HEService - PartialRelinKeyAggregation,2.379958ms,Client1,2.379958,5073.454,5075.833958,22.659248,25.039206
6,2025/07/22,14:41:31.197952,startEncryptionSetupPhaseFor,5.233553417s,AggregationService,5233.553417,5233.596,10467.149417,25.039206,5258.592623
7,2025/07/22,14:41:34.049860,addClient,833ns,AggregationService,0.000833,8085.504,8085.504833,5258.592623,5258.593456
8,2025/07/22,14:41:34.060062,DataSpaceClientService - RegisterClient,12.486834ms,Client2,12.486834,8095.706,8108.192834,5258.593456,5271.080290
9,2025/07/22,14:41:34.068452,HEService - SetParameters,8.336709ms,Client2,8.336709,8104.096,8112.432709,5271.080290,5279.416999
10,2025/07/22,14:41:39.057244,HEService - PartialShareAggregation,2.375µs,Client1,0.002375,13092.888,13092.890375,5279.416999,5279.419374
11,2025/07/22,14:41:39.058305,HEService - PartialShareAggregation,1.5µs,Client2,0.001500,13093.949,13093.950500,5279.419374,5279.420874
12,2025/07/22,14:41:39.062853,EncryptionHandler - handleReceivePublicKey,1.256417ms,Client1,1.256417,13098.497,13099.753417,5279.420874,5280.677291
13,2025/07/22,14:41:39.064792,EncryptionHandler - handleReceivePublicKey,1.117458ms,Client2,1.117458,13100.436,13101.553458,5280.677291,5281.794749
14,2025/07/22,14:41:39.082244,HEService - PartialRelinKeyAggregation,2.257125ms,Client1,2.257125,13117.888,13120.145125,5281.794749,5284.051874
15,2025/07/22,14:41:39.259197,HEService - PartialRelinKeyAggregation,2.449458ms,Client2,2.449458,13294.841,13297.290458,5284.051874,5286.501332
16,2025/07/22,14:41:39.414548,startEncryptionSetupPhaseFor,5.36460525s,AggregationService,5364.605250,13450.192,18814.797250,5286.501332,10651.106582

In [86]:
df = px.data.tips()
fig = px.bar(initializiation_data, base="StartMs", x="runtime_ms", y="Service", color='Name', orientation='h',
             hover_data=["EndTime", "StartMs", "runtime_ms"], color_discrete_sequence=px.colors.qualitative.Safe,
             height=400)
fig.show()

In [87]:
request_client_training = data_joined.loc[data_joined["Name"] == "requestClientTraining"].index

print(request_client_training[0])
print(request_client_training[1])

data_after_upload = data_joined[request_client_training[0]:request_client_training[1]]
data_after_upload

17
31

,Date,EndTime,Name,Runtime,Service,runtime_ms,StartMs,EndMs,Start_without_offset,End_without_offset
17,2025/07/22,14:41:53.083988,requestClientTraining,4.722084ms,AggregationService,4.722084,27119.632,27124.354084,10651.106582,10655.828666
18,2025/07/22,14:42:05.271684,HEService - Encrypt,861.965792ms,Client1,861.965792,39307.328,40169.293792,10655.828666,11517.794458
19,2025/07/22,14:42:05.300475,HEService - Encrypt,864.07375ms,Client2,864.073750,39336.119,40200.192750,11517.794458,12381.868208
20,2025/07/22,14:42:06.613421,DataSpaceClientService - UploadData,1.30605325s,Client1,1306.053250,40649.065,41955.118250,12381.868208,13687.921458
21,2025/07/22,14:42:06.638348,DataSpaceClientService - UploadData,1.300053334s,Client2,1300.053334,40673.992,41974.045334,13687.921458,14987.974792
22,2025/07/22,14:42:24.106563,aggregateWeights,49.423458ms,AggregationService,49.423458,58142.207,58191.630458,14987.974792,15037.398250
23,2025/07/22,14:42:24.294186,HEService - PublicKeySwitchGeneration,29.733375ms,Client1,29.733375,58329.830,58359.563375,15037.398250,15067.131625
24,2025/07/22,14:42:24.294211,EncryptionHandler - handlePublicKeySwitch,106.144666ms,Client1,106.144666,58329.855,58435.999666,15067.131625,15173.276291
25,2025/07/22,14:42:24.485745,HEService - PublicKeySwitchGeneration,29.365167ms,Client2,29.365167,58521.389,58550.754167,15173.276291,15202.641458
26,2025/07/22,14:42:24.485772,EncryptionHandler - handlePublicKeySwitch,104.59125ms,Client2,104.591250,58521.416,58626.007250,15202.641458,15307.232708
27,2025/07/22,14:42:24.485907,initiateKeySwitchGeneration,379.262666ms,AggregationService,379.262666,58521.551,58900.813666,15307.232708,15686.495374
28,2025/07/22,14:42:24.486488,EncryptionHandler - handlePublicKeySwitchAggre...,6.625µs,Client2,0.006625,58522.132,58522.138625,15686.495374,15686.501999
29,2025/07/22,14:42:24.487010,EncryptionHandler - handlePublicKeySwitchAggre...,5.791µs,Client1,0.005791,58522.654,58522.659791,15686.501999,15686.507790
30,2025/07/22,14:42:27.629453,updateClientModels,2.239003917s,AggregationService,2239.003917,61665.097,63904.100917,15686.507790,17925.511707

In [88]:
df = px.data.tips()
fig = px.bar(data_after_upload, base="StartMs", x="runtime_ms", y="Service", color='Name', orientation='h',
             hover_data=["EndTime", "StartMs", "runtime_ms"], color_discrete_sequence=px.colors.qualitative.Safe,
             height=400)
fig.show()