In [1]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio

In [2]:
LOG_DIR = "../logs/"

AGG_LOG = "he-aggregation-service"
CLIENT1_LOG = "he-client-1-go"
CLIENT2_LOG = "he-client-2-go"

In [3]:
agg_time = pd.read_csv(f"{LOG_DIR}{AGG_LOG}-time.csv")
client1_time = pd.read_csv(f"{LOG_DIR}{CLIENT1_LOG}-time.csv")
client2_time = pd.read_csv(f"{LOG_DIR}{CLIENT2_LOG}-time.csv")

agg_time["Service"] = "AggregationService"
client1_time["Service"] = "Client1"
client2_time["Service"] = "Client2"

client1_time.head()

,Date,EndTime,Name,Runtime,Service
0,2025/07/22,16:42:45.854911,DataSpaceClientService - RegisterClient,17.285958ms,Client1
1,2025/07/22,16:42:45.863316,HEService - SetParameters,8.358917ms,Client1
2,2025/07/22,16:42:50.867832,HEService - PartialShareAggregation,1.084µs,Client1
3,2025/07/22,16:42:50.872998,EncryptionHandler - handleReceivePublicKey,1.315917ms,Client1
4,2025/07/22,16:42:50.904355,HEService - PartialRelinKeyAggregation,2.48075ms,Client1

In [4]:
data_joined = pd.concat(
    [agg_time, client1_time, client2_time],
    axis=0)

data_joined = data_joined.reset_index(drop=True)

data_joined

,Date,EndTime,Name,Runtime,Service
0,2025/07/22,16:42:45.841870,addClient,1.708µs,AggregationService
1,2025/07/22,16:42:51.065956,startEncryptionSetupPhaseFor,5.224059s,AggregationService
2,2025/07/22,16:42:53.846724,addClient,1.292µs,AggregationService
3,2025/07/22,16:42:59.221070,startEncryptionSetupPhaseFor,5.37431925s,AggregationService
4,2025/07/22,16:43:09.286822,requestClientTraining,4.1685ms,AggregationService
5,2025/07/22,16:43:25.141169,aggregateWeights,56.834709ms,AggregationService
6,2025/07/22,16:43:25.538867,initiateKeySwitchGeneration,397.6255ms,AggregationService
7,2025/07/22,16:43:28.692864,updateClientModels,2.229893459s,AggregationService
8,2025/07/22,16:43:32.626307,requestClientTraining,3.368667ms,AggregationService
9,2025/07/22,16:43:50.128681,aggregateWeights,54.808708ms,AggregationService
10,2025/07/22,16:43:50.412411,initiateKeySwitchGeneration,283.656ms,AggregationService
11,2025/07/22,16:43:53.533310,updateClientModels,2.207892792s,AggregationService
12,2025/07/22,16:43:59.294675,requestClientTraining,25.583792ms,AggregationService
13,2025/07/22,16:44:15.151077,aggregateWeights,54.624833ms,AggregationService
14,2025/07/22,16:44:15.570328,initiateKeySwitchGeneration,419.174ms,AggregationService
15,2025/07/22,16:44:18.698909,updateClientModels,2.210517166s,AggregationService
16,2025/07/22,16:42:45.854911,DataSpaceClientService - RegisterClient,17.285958ms,Client1
17,2025/07/22,16:42:45.863316,HEService - SetParameters,8.358917ms,Client1
18,2025/07/22,16:42:50.867832,HEService - PartialShareAggregation,1.084µs,Client1
19,2025/07/22,16:42:50.872998,EncryptionHandler - handleReceivePublicKey,1.315917ms,Client1
20,2025/07/22,16:42:50.904355,HEService - PartialRelinKeyAggregation,2.48075ms,Client1
21,2025/07/22,16:42:58.854589,HEService - PartialShareAggregation,1.75µs,Client1
22,2025/07/22,16:42:58.860615,EncryptionHandler - handleReceivePublicKey,1.569333ms,Client1
23,2025/07/22,16:42:58.881874,HEService - PartialRelinKeyAggregation,2.422792ms,Client1
24,2025/07/22,16:43:22.128913,HEService - Encrypt,881.40125ms,Client1
25,2025/07/22,16:43:23.424320,DataSpaceClientService - UploadData,1.249576167s,Client1
26,2025/07/22,16:43:25.337108,HEService - PublicKeySwitchGeneration,30.754458ms,Client1
27,2025/07/22,16:43:25.337140,EncryptionHandler - handlePublicKeySwitch,107.125417ms,Client1
28,2025/07/22,16:43:25.539497,EncryptionHandler - handlePublicKeySwitchAggre...,7.333µs,Client1
29,2025/07/22,16:43:45.095335,HEService - Encrypt,854.632458ms,Client1
30,2025/07/22,16:43:46.242709,DataSpaceClientService - UploadData,1.116345167s,Client1
31,2025/07/22,16:43:50.278805,HEService - PublicKeySwitchGeneration,29.224667ms,Client1
32,2025/07/22,16:43:50.278883,EncryptionHandler - handlePublicKeySwitch,98.359083ms,Client1
33,2025/07/22,16:43:50.413017,EncryptionHandler - handlePublicKeySwitchAggre...,24.916µs,Client1
34,2025/07/22,16:44:11.311717,HEService - Encrypt,848.283667ms,Client1
35,2025/07/22,16:44:12.500789,DataSpaceClientService - UploadData,1.163255792s,Client1
36,2025/07/22,16:44:15.332222,HEService - PublicKeySwitchGeneration,29.499958ms,Client1
37,2025/07/22,16:44:15.332249,EncryptionHandler - handlePublicKeySwitch,142.670916ms,Client1
38,2025/07/22,16:44:15.570967,EncryptionHandler - handlePublicKeySwitchAggre...,7.417µs,Client1
39,2025/07/22,16:42:53.857312,DataSpaceClientService - RegisterClient,12.761208ms,Client2
40,2025/07/22,16:42:53.865943,HEService - SetParameters,8.578583ms,Client2
41,2025/07/22,16:42:58.855781,HEService - PartialShareAggregation,2.333µs,Client2
42,2025/07/22,16:42:58.863080,EncryptionHandler - handleReceivePublicKey,1.570916ms,Client2
43,2025/07/22,16:42:59.063884,HEService - PartialRelinKeyAggregation,2.646667ms,Client2
44,2025/07/22,16:43:22.080275,HEService - Encrypt,877.91425ms,Client2
45,2025/07/22,16:43:23.387515,DataSpaceClientService - UploadData,1.260182542s,Client2
46,2025/07/22,16:43:25.538703,HEService - PublicKeySwitchGeneration,30.010208ms,Client2
47,2025/07/22,16:43:25.538735,EncryptionHandler - handlePublicKeySwitch,106.422542ms,Client2
48,2025/07/22,16:43:25.540009,EncryptionHandler - handlePublicKeySwitchAggre...,13.166µs,Client2
49,2025/07/22,16:43:45.040738,HEService - Encrypt,841.901625ms,Client2
50,2025/07/22,16:43:46.161624,DataSpaceClientService - UploadData,1.093626417s,Client2
51,2025/07/22,16:43:50.412243,HEService - PublicKeySwitchGeneration,29.064834ms,Client2
52,2025/07/22,16:43:50.412272,EncryptionHandler - handlePublicKeySwitch,98.4025ms,Client2
53,2025/07/22,16:43:50.413632,EncryptionHandler - handlePublicKeySwitchAggre...,6.917µs,Client2
54,2025/07/22,16:44:11.447461,HEService - Encrypt,863.304917ms,Client2
55,2025/07/22,16:44:12.615570,DataSpaceClientService - UploadData,1.137182459s,Client2
56,2025/07/22,16:44:15.570098,HEService - PublicKeySwitchGeneration,28.609625ms,Client2
57,2025/07/22,16:44:15.570135,EncryptionHandler - handlePublicKeySwitch,199.015875ms,Client2
58,2025/07/22,16:44:15.572985,EncryptionHandler - handlePublicKeySwitchAggre...,6.916µs,Client2

In [5]:
def parse_duration_to_ms(time_str):
    """Parse milliseconds, microseconds, nanoseconds or seconds from a string."""
    if "ms" in time_str:
        return float(time_str.replace("ms", "").strip())
    elif "us" in time_str:
        return float(time_str.replace("us", "").strip()) / 1000.0
    elif "µs" in time_str:
        return float(time_str.replace("µs", "").strip()) / 1000.0
    elif "ns" in time_str:
        return float(time_str.replace("ns", "").strip()) / 1_000_000.0
    elif "s" in time_str:
        return float(time_str.replace("s", "").strip()) * 1000.0
    else:
        raise ValueError(f"Unknown time format: {time_str}")


def create_timeline_offset(df):
    """Create a timeline with an offset for the x-axis."""
    min_time = df["EndTime"].min()
    df["StartMs"] = (pd.to_datetime(df["EndTime"], format="%H:%M:%S.%f") - pd.to_datetime(min_time, format="%H:%M:%S.%f")).dt.total_seconds() * 1000
    
    return df
    
#agg_time["runtime_ms"] = agg_time["Runtime"].apply(parse_duration_to_ms)
#client1_time["runtime_ms"] = client1_time["Runtime"].apply(parse_duration_to_ms)
#client2_time["runtime_ms"] = client2_time["Runtime"].apply(parse_duration_to_ms)
data_joined["runtime_ms"] = data_joined["Runtime"].apply(parse_duration_to_ms)

#agg_time = create_timeline_offset(agg_time)
#client1_time = create_timeline_offset(client1_time)
#client2_time = create_timeline_offset(client2_time)
data_joined = create_timeline_offset(data_joined)

data_joined["EndMs"] = data_joined["StartMs"] + data_joined["runtime_ms"]

data_joined = data_joined.sort_values(by=["StartMs", "EndMs"])
data_joined.reset_index(drop=True, inplace=True)
data_joined

,Date,EndTime,Name,Runtime,Service,runtime_ms,StartMs,EndMs
0,2025/07/22,16:42:45.841870,addClient,1.708µs,AggregationService,0.001708,0.000,0.001708
1,2025/07/22,16:42:45.854911,DataSpaceClientService - RegisterClient,17.285958ms,Client1,17.285958,13.041,30.326958
2,2025/07/22,16:42:45.863316,HEService - SetParameters,8.358917ms,Client1,8.358917,21.446,29.804917
3,2025/07/22,16:42:50.867832,HEService - PartialShareAggregation,1.084µs,Client1,0.001084,5025.962,5025.963084
4,2025/07/22,16:42:50.872998,EncryptionHandler - handleReceivePublicKey,1.315917ms,Client1,1.315917,5031.128,5032.443917
5,2025/07/22,16:42:50.904355,HEService - PartialRelinKeyAggregation,2.48075ms,Client1,2.480750,5062.485,5064.965750
6,2025/07/22,16:42:51.065956,startEncryptionSetupPhaseFor,5.224059s,AggregationService,5224.059000,5224.086,10448.145000
7,2025/07/22,16:42:53.846724,addClient,1.292µs,AggregationService,0.001292,8004.854,8004.855292
8,2025/07/22,16:42:53.857312,DataSpaceClientService - RegisterClient,12.761208ms,Client2,12.761208,8015.442,8028.203208
9,2025/07/22,16:42:53.865943,HEService - SetParameters,8.578583ms,Client2,8.578583,8024.073,8032.651583
10,2025/07/22,16:42:58.854589,HEService - PartialShareAggregation,1.75µs,Client1,0.001750,13012.719,13012.720750
11,2025/07/22,16:42:58.855781,HEService - PartialShareAggregation,2.333µs,Client2,0.002333,13013.911,13013.913333
12,2025/07/22,16:42:58.860615,EncryptionHandler - handleReceivePublicKey,1.569333ms,Client1,1.569333,13018.745,13020.314333
13,2025/07/22,16:42:58.863080,EncryptionHandler - handleReceivePublicKey,1.570916ms,Client2,1.570916,13021.210,13022.780916
14,2025/07/22,16:42:58.881874,HEService - PartialRelinKeyAggregation,2.422792ms,Client1,2.422792,13040.004,13042.426792
15,2025/07/22,16:42:59.063884,HEService - PartialRelinKeyAggregation,2.646667ms,Client2,2.646667,13222.014,13224.660667
16,2025/07/22,16:42:59.221070,startEncryptionSetupPhaseFor,5.37431925s,AggregationService,5374.319250,13379.200,18753.519250
17,2025/07/22,16:43:09.286822,requestClientTraining,4.1685ms,AggregationService,4.168500,23444.952,23449.120500
18,2025/07/22,16:43:22.080275,HEService - Encrypt,877.91425ms,Client2,877.914250,36238.405,37116.319250
19,2025/07/22,16:43:22.128913,HEService - Encrypt,881.40125ms,Client1,881.401250,36287.043,37168.444250
20,2025/07/22,16:43:23.387515,DataSpaceClientService - UploadData,1.260182542s,Client2,1260.182542,37545.645,38805.827542
21,2025/07/22,16:43:23.424320,DataSpaceClientService - UploadData,1.249576167s,Client1,1249.576167,37582.450,38832.026167
22,2025/07/22,16:43:25.141169,aggregateWeights,56.834709ms,AggregationService,56.834709,39299.299,39356.133709
23,2025/07/22,16:43:25.337108,HEService - PublicKeySwitchGeneration,30.754458ms,Client1,30.754458,39495.238,39525.992458
24,2025/07/22,16:43:25.337140,EncryptionHandler - handlePublicKeySwitch,107.125417ms,Client1,107.125417,39495.270,39602.395417
25,2025/07/22,16:43:25.538703,HEService - PublicKeySwitchGeneration,30.010208ms,Client2,30.010208,39696.833,39726.843208
26,2025/07/22,16:43:25.538735,EncryptionHandler - handlePublicKeySwitch,106.422542ms,Client2,106.422542,39696.865,39803.287542
27,2025/07/22,16:43:25.538867,initiateKeySwitchGeneration,397.6255ms,AggregationService,397.625500,39696.997,40094.622500
28,2025/07/22,16:43:25.539497,EncryptionHandler - handlePublicKeySwitchAggre...,7.333µs,Client1,0.007333,39697.627,39697.634333
29,2025/07/22,16:43:25.540009,EncryptionHandler - handlePublicKeySwitchAggre...,13.166µs,Client2,0.013166,39698.139,39698.152166
30,2025/07/22,16:43:28.692864,updateClientModels,2.229893459s,AggregationService,2229.893459,42850.994,45080.887459
31,2025/07/22,16:43:32.626307,requestClientTraining,3.368667ms,AggregationService,3.368667,46784.437,46787.805667
32,2025/07/22,16:43:45.040738,HEService - Encrypt,841.901625ms,Client2,841.901625,59198.868,60040.769625
33,2025/07/22,16:43:45.095335,HEService - Encrypt,854.632458ms,Client1,854.632458,59253.465,60108.097458
34,2025/07/22,16:43:46.161624,DataSpaceClientService - UploadData,1.093626417s,Client2,1093.626417,60319.754,61413.380417
35,2025/07/22,16:43:46.242709,DataSpaceClientService - UploadData,1.116345167s,Client1,1116.345167,60400.839,61517.184167
36,2025/07/22,16:43:50.128681,aggregateWeights,54.808708ms,AggregationService,54.808708,64286.811,64341.619708
37,2025/07/22,16:43:50.278805,HEService - PublicKeySwitchGeneration,29.224667ms,Client1,29.224667,64436.935,64466.159667
38,2025/07/22,16:43:50.278883,EncryptionHandler - handlePublicKeySwitch,98.359083ms,Client1,98.359083,64437.013,64535.372083
39,2025/07/22,16:43:50.412243,HEService - PublicKeySwitchGeneration,29.064834ms,Client2,29.064834,64570.373,64599.437834
40,2025/07/22,16:43:50.412272,EncryptionHandler - handlePublicKeySwitch,98.4025ms,Client2,98.402500,64570.402,64668.804500
41,2025/07/22,16:43:50.412411,initiateKeySwitchGeneration,283.656ms,AggregationService,283.656000,64570.541,64854.197000
42,2025/07/22,16:43:50.413017,EncryptionHandler - handlePublicKeySwitchAggre...,24.916µs,Client1,0.024916,64571.147,64571.171916
43,2025/07/22,16:43:50.413632,EncryptionHandler - handlePublicKeySwitchAggre...,6.917µs,Client2,0.006917,64571.762,64571.768917
44,2025/07/22,16:43:53.533310,updateClientModels,2.207892792s,AggregationService,2207.892792,67691.440,69899.332792
45,2025/07/22,16:43:59.294675,requestClientTraining,25.583792ms,AggregationService,25.583792,73452.805,73478.388792
46,2025/07/22,16:44:11.311717,HEService - Encrypt,848.283667ms,Client1,848.283667,85469.847,86318.130667
47,2025/07/22,16:44:11.447461,HEService - Encrypt,863.304917ms,Client2,863.304917,85605.591,86468.895917
48,2025/07/22,16:44:12.500789,DataSpaceClientService - UploadData,1.163255792s,Client1,1163.255792,86658.919,87822.174792
49,2025/07/22,16:44:12.615570,DataSpaceClientService - UploadData,1.137182459s,Client2,1137.182459,86773.700,87910.882459
50,2025/07/22,16:44:15.151077,aggregateWeights,54.624833ms,AggregationService,54.624833,89309.207,89363.831833
51,2025/07/22,16:44:15.332222,HEService - PublicKeySwitchGeneration,29.499958ms,Client1,29.499958,89490.352,89519.851958
52,2025/07/22,16:44:15.332249,EncryptionHandler - handlePublicKeySwitch,142.670916ms,Client1,142.670916,89490.379,89633.049916
53,2025/07/22,16:44:15.570098,HEService - PublicKeySwitchGeneration,28.609625ms,Client2,28.609625,89728.228,89756.837625
54,2025/07/22,16:44:15.570135,EncryptionHandler - handlePublicKeySwitch,199.015875ms,Client2,199.015875,89728.265,89927.280875
55,2025/07/22,16:44:15.570328,initiateKeySwitchGeneration,419.174ms,AggregationService,419.174000,89728.458,90147.632000
56,2025/07/22,16:44:15.570967,EncryptionHandler - handlePublicKeySwitchAggre...,7.417µs,Client1,0.007417,89729.097,89729.104417
57,2025/07/22,16:44:15.572985,EncryptionHandler - handlePublicKeySwitchAggre...,6.916µs,Client2,0.006916,89731.115,89731.121916
58,2025/07/22,16:44:18.698909,updateClientModels,2.210517166s,AggregationService,2210.517166,92857.039,95067.556166

In [6]:
print(pio.templates)

pio.templates["research"] = go.layout.Template(
    layout=dict(
        font=dict(color="#000000"),
        paper_bgcolor="#ffffff",
        plot_bgcolor="#ffffff",
        hovermode="closest",
        xaxis=dict(
            tickangle=-45,
            showline=True,
            linewidth=1,
            linecolor="#373737",
            ticks="inside",
            showgrid=True,
            gridcolor="#373737",
            zeroline=True,
            zerolinecolor="#373737",
            zerolinewidth=1,
            mirror=True
        ),
        yaxis=dict(
            showline=True,
            linewidth=1,
            linecolor="#373737",
            ticks="inside",
            showgrid=True,
            gridcolor="#373737",
            zeroline=True,
            zerolinecolor="#373737",
            zerolinewidth=1,
            mirror=True
        ),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=-0.5,
            xanchor="right",
            x=0.95
        ),
    )
)

pio.templates.default = "plotly_white+research"

Templates configuration
-----------------------
    Default template: 'plotly'
    Available templates:
        ['ggplot2', 'seaborn', 'simple_white', 'plotly',
         'plotly_white', 'plotly_dark', 'presentation', 'xgridoff',
         'ygridoff', 'gridon', 'none']

In [15]:
import plotly.express as px
import plotly.graph_objects as go


df = px.data.tips()
fig = px.bar(data_joined[data_joined["runtime_ms"] >= 100], base="StartMs", x="runtime_ms", y="Service", color='Name', orientation='h',
             hover_data=["EndTime", "StartMs", "runtime_ms"], labels={"runtime_ms": "Runtime in millisecond", "Service": "Service"}, color_discrete_sequence=px.colors.qualitative.Safe,
             height=400)
fig.show()

In [8]:
# remove all waiting times

data_joined.at[data_joined.index[0], "Start_without_offset"] = data_joined.at[data_joined.index[0], "StartMs"]
data_joined.at[data_joined.index[0], "End_without_offset"] = data_joined.at[data_joined.index[0], "EndMs"]

for i in range(1, len(data_joined)):
    data_joined.at[data_joined.index[i], "Start_without_offset"] = data_joined.iloc[i-1]["End_without_offset"]
    data_joined.at[data_joined.index[i], "End_without_offset"] = data_joined.at[data_joined.index[i], "Start_without_offset"] + data_joined.at[data_joined.index[i], "runtime_ms"]
data_joined

,Date,EndTime,Name,Runtime,Service,runtime_ms,StartMs,EndMs,Start_without_offset,End_without_offset
0,2025/07/22,16:42:45.841870,addClient,1.708µs,AggregationService,0.001708,0.000,0.001708,0.000000,0.001708
1,2025/07/22,16:42:45.854911,DataSpaceClientService - RegisterClient,17.285958ms,Client1,17.285958,13.041,30.326958,0.001708,17.287666
2,2025/07/22,16:42:45.863316,HEService - SetParameters,8.358917ms,Client1,8.358917,21.446,29.804917,17.287666,25.646583
3,2025/07/22,16:42:50.867832,HEService - PartialShareAggregation,1.084µs,Client1,0.001084,5025.962,5025.963084,25.646583,25.647667
4,2025/07/22,16:42:50.872998,EncryptionHandler - handleReceivePublicKey,1.315917ms,Client1,1.315917,5031.128,5032.443917,25.647667,26.963584
5,2025/07/22,16:42:50.904355,HEService - PartialRelinKeyAggregation,2.48075ms,Client1,2.480750,5062.485,5064.965750,26.963584,29.444334
6,2025/07/22,16:42:51.065956,startEncryptionSetupPhaseFor,5.224059s,AggregationService,5224.059000,5224.086,10448.145000,29.444334,5253.503334
7,2025/07/22,16:42:53.846724,addClient,1.292µs,AggregationService,0.001292,8004.854,8004.855292,5253.503334,5253.504626
8,2025/07/22,16:42:53.857312,DataSpaceClientService - RegisterClient,12.761208ms,Client2,12.761208,8015.442,8028.203208,5253.504626,5266.265834
9,2025/07/22,16:42:53.865943,HEService - SetParameters,8.578583ms,Client2,8.578583,8024.073,8032.651583,5266.265834,5274.844417
10,2025/07/22,16:42:58.854589,HEService - PartialShareAggregation,1.75µs,Client1,0.001750,13012.719,13012.720750,5274.844417,5274.846167
11,2025/07/22,16:42:58.855781,HEService - PartialShareAggregation,2.333µs,Client2,0.002333,13013.911,13013.913333,5274.846167,5274.848500
12,2025/07/22,16:42:58.860615,EncryptionHandler - handleReceivePublicKey,1.569333ms,Client1,1.569333,13018.745,13020.314333,5274.848500,5276.417833
13,2025/07/22,16:42:58.863080,EncryptionHandler - handleReceivePublicKey,1.570916ms,Client2,1.570916,13021.210,13022.780916,5276.417833,5277.988749
14,2025/07/22,16:42:58.881874,HEService - PartialRelinKeyAggregation,2.422792ms,Client1,2.422792,13040.004,13042.426792,5277.988749,5280.411541
15,2025/07/22,16:42:59.063884,HEService - PartialRelinKeyAggregation,2.646667ms,Client2,2.646667,13222.014,13224.660667,5280.411541,5283.058208
16,2025/07/22,16:42:59.221070,startEncryptionSetupPhaseFor,5.37431925s,AggregationService,5374.319250,13379.200,18753.519250,5283.058208,10657.377458
17,2025/07/22,16:43:09.286822,requestClientTraining,4.1685ms,AggregationService,4.168500,23444.952,23449.120500,10657.377458,10661.545958
18,2025/07/22,16:43:22.080275,HEService - Encrypt,877.91425ms,Client2,877.914250,36238.405,37116.319250,10661.545958,11539.460208
19,2025/07/22,16:43:22.128913,HEService - Encrypt,881.40125ms,Client1,881.401250,36287.043,37168.444250,11539.460208,12420.861458
20,2025/07/22,16:43:23.387515,DataSpaceClientService - UploadData,1.260182542s,Client2,1260.182542,37545.645,38805.827542,12420.861458,13681.044000
21,2025/07/22,16:43:23.424320,DataSpaceClientService - UploadData,1.249576167s,Client1,1249.576167,37582.450,38832.026167,13681.044000,14930.620167
22,2025/07/22,16:43:25.141169,aggregateWeights,56.834709ms,AggregationService,56.834709,39299.299,39356.133709,14930.620167,14987.454876
23,2025/07/22,16:43:25.337108,HEService - PublicKeySwitchGeneration,30.754458ms,Client1,30.754458,39495.238,39525.992458,14987.454876,15018.209334
24,2025/07/22,16:43:25.337140,EncryptionHandler - handlePublicKeySwitch,107.125417ms,Client1,107.125417,39495.270,39602.395417,15018.209334,15125.334751
25,2025/07/22,16:43:25.538703,HEService - PublicKeySwitchGeneration,30.010208ms,Client2,30.010208,39696.833,39726.843208,15125.334751,15155.344959
26,2025/07/22,16:43:25.538735,EncryptionHandler - handlePublicKeySwitch,106.422542ms,Client2,106.422542,39696.865,39803.287542,15155.344959,15261.767501
27,2025/07/22,16:43:25.538867,initiateKeySwitchGeneration,397.6255ms,AggregationService,397.625500,39696.997,40094.622500,15261.767501,15659.393001
28,2025/07/22,16:43:25.539497,EncryptionHandler - handlePublicKeySwitchAggre...,7.333µs,Client1,0.007333,39697.627,39697.634333,15659.393001,15659.400334
29,2025/07/22,16:43:25.540009,EncryptionHandler - handlePublicKeySwitchAggre...,13.166µs,Client2,0.013166,39698.139,39698.152166,15659.400334,15659.413500
30,2025/07/22,16:43:28.692864,updateClientModels,2.229893459s,AggregationService,2229.893459,42850.994,45080.887459,15659.413500,17889.306959
31,2025/07/22,16:43:32.626307,requestClientTraining,3.368667ms,AggregationService,3.368667,46784.437,46787.805667,17889.306959,17892.675626
32,2025/07/22,16:43:45.040738,HEService - Encrypt,841.901625ms,Client2,841.901625,59198.868,60040.769625,17892.675626,18734.577251
33,2025/07/22,16:43:45.095335,HEService - Encrypt,854.632458ms,Client1,854.632458,59253.465,60108.097458,18734.577251,19589.209709
34,2025/07/22,16:43:46.161624,DataSpaceClientService - UploadData,1.093626417s,Client2,1093.626417,60319.754,61413.380417,19589.209709,20682.836126
35,2025/07/22,16:43:46.242709,DataSpaceClientService - UploadData,1.116345167s,Client1,1116.345167,60400.839,61517.184167,20682.836126,21799.181293
36,2025/07/22,16:43:50.128681,aggregateWeights,54.808708ms,AggregationService,54.808708,64286.811,64341.619708,21799.181293,21853.990001
37,2025/07/22,16:43:50.278805,HEService - PublicKeySwitchGeneration,29.224667ms,Client1,29.224667,64436.935,64466.159667,21853.990001,21883.214668
38,2025/07/22,16:43:50.278883,EncryptionHandler - handlePublicKeySwitch,98.359083ms,Client1,98.359083,64437.013,64535.372083,21883.214668,21981.573751
39,2025/07/22,16:43:50.412243,HEService - PublicKeySwitchGeneration,29.064834ms,Client2,29.064834,64570.373,64599.437834,21981.573751,22010.638585
40,2025/07/22,16:43:50.412272,EncryptionHandler - handlePublicKeySwitch,98.4025ms,Client2,98.402500,64570.402,64668.804500,22010.638585,22109.041085
41,2025/07/22,16:43:50.412411,initiateKeySwitchGeneration,283.656ms,AggregationService,283.656000,64570.541,64854.197000,22109.041085,22392.697085
42,2025/07/22,16:43:50.413017,EncryptionHandler - handlePublicKeySwitchAggre...,24.916µs,Client1,0.024916,64571.147,64571.171916,22392.697085,22392.722001
43,2025/07/22,16:43:50.413632,EncryptionHandler - handlePublicKeySwitchAggre...,6.917µs,Client2,0.006917,64571.762,64571.768917,22392.722001,22392.728918
44,2025/07/22,16:43:53.533310,updateClientModels,2.207892792s,AggregationService,2207.892792,67691.440,69899.332792,22392.728918,24600.621710
45,2025/07/22,16:43:59.294675,requestClientTraining,25.583792ms,AggregationService,25.583792,73452.805,73478.388792,24600.621710,24626.205502
46,2025/07/22,16:44:11.311717,HEService - Encrypt,848.283667ms,Client1,848.283667,85469.847,86318.130667,24626.205502,25474.489169
47,2025/07/22,16:44:11.447461,HEService - Encrypt,863.304917ms,Client2,863.304917,85605.591,86468.895917,25474.489169,26337.794086
48,2025/07/22,16:44:12.500789,DataSpaceClientService - UploadData,1.163255792s,Client1,1163.255792,86658.919,87822.174792,26337.794086,27501.049878
49,2025/07/22,16:44:12.615570,DataSpaceClientService - UploadData,1.137182459s,Client2,1137.182459,86773.700,87910.882459,27501.049878,28638.232337
50,2025/07/22,16:44:15.151077,aggregateWeights,54.624833ms,AggregationService,54.624833,89309.207,89363.831833,28638.232337,28692.857170
51,2025/07/22,16:44:15.332222,HEService - PublicKeySwitchGeneration,29.499958ms,Client1,29.499958,89490.352,89519.851958,28692.857170,28722.357128
52,2025/07/22,16:44:15.332249,EncryptionHandler - handlePublicKeySwitch,142.670916ms,Client1,142.670916,89490.379,89633.049916,28722.357128,28865.028044
53,2025/07/22,16:44:15.570098,HEService - PublicKeySwitchGeneration,28.609625ms,Client2,28.609625,89728.228,89756.837625,28865.028044,28893.637669
54,2025/07/22,16:44:15.570135,EncryptionHandler - handlePublicKeySwitch,199.015875ms,Client2,199.015875,89728.265,89927.280875,28893.637669,29092.653544
55,2025/07/22,16:44:15.570328,initiateKeySwitchGeneration,419.174ms,AggregationService,419.174000,89728.458,90147.632000,29092.653544,29511.827544
56,2025/07/22,16:44:15.570967,EncryptionHandler - handlePublicKeySwitchAggre...,7.417µs,Client1,0.007417,89729.097,89729.104417,29511.827544,29511.834961
57,2025/07/22,16:44:15.572985,EncryptionHandler - handlePublicKeySwitchAggre...,6.916µs,Client2,0.006916,89731.115,89731.121916,29511.834961,29511.841877
58,2025/07/22,16:44:18.698909,updateClientModels,2.210517166s,AggregationService,2210.517166,92857.039,95067.556166,29511.841877,31722.359043

In [ ]:
df = px.data.tips()
fig = px.bar(data_joined, base="Start_without_offset", x="runtime_ms", y="Service", color='Name', orientation='h',
             hover_data=["EndTime", "StartMs", "runtime_ms"], labels={"runtime_ms": "Runtime in millisecond", "Service": "Service"}, color_discrete_sequence=px.colors.qualitative.Safe,
             height=400)
fig.show()

In [10]:
data_joined.reset_index(drop=True, inplace=True)

first_occ_encrypt = data_joined.loc[data_joined["Name"] == "requestClientTraining"].index[0]
print(first_occ_encrypt)

initializiation_data = data_joined[:first_occ_encrypt]
initializiation_data

17

,Date,EndTime,Name,Runtime,Service,runtime_ms,StartMs,EndMs,Start_without_offset,End_without_offset
0,2025/07/22,16:42:45.841870,addClient,1.708µs,AggregationService,0.001708,0.000,0.001708,0.000000,0.001708
1,2025/07/22,16:42:45.854911,DataSpaceClientService - RegisterClient,17.285958ms,Client1,17.285958,13.041,30.326958,0.001708,17.287666
2,2025/07/22,16:42:45.863316,HEService - SetParameters,8.358917ms,Client1,8.358917,21.446,29.804917,17.287666,25.646583
3,2025/07/22,16:42:50.867832,HEService - PartialShareAggregation,1.084µs,Client1,0.001084,5025.962,5025.963084,25.646583,25.647667
4,2025/07/22,16:42:50.872998,EncryptionHandler - handleReceivePublicKey,1.315917ms,Client1,1.315917,5031.128,5032.443917,25.647667,26.963584
5,2025/07/22,16:42:50.904355,HEService - PartialRelinKeyAggregation,2.48075ms,Client1,2.480750,5062.485,5064.965750,26.963584,29.444334
6,2025/07/22,16:42:51.065956,startEncryptionSetupPhaseFor,5.224059s,AggregationService,5224.059000,5224.086,10448.145000,29.444334,5253.503334
7,2025/07/22,16:42:53.846724,addClient,1.292µs,AggregationService,0.001292,8004.854,8004.855292,5253.503334,5253.504626
8,2025/07/22,16:42:53.857312,DataSpaceClientService - RegisterClient,12.761208ms,Client2,12.761208,8015.442,8028.203208,5253.504626,5266.265834
9,2025/07/22,16:42:53.865943,HEService - SetParameters,8.578583ms,Client2,8.578583,8024.073,8032.651583,5266.265834,5274.844417
10,2025/07/22,16:42:58.854589,HEService - PartialShareAggregation,1.75µs,Client1,0.001750,13012.719,13012.720750,5274.844417,5274.846167
11,2025/07/22,16:42:58.855781,HEService - PartialShareAggregation,2.333µs,Client2,0.002333,13013.911,13013.913333,5274.846167,5274.848500
12,2025/07/22,16:42:58.860615,EncryptionHandler - handleReceivePublicKey,1.569333ms,Client1,1.569333,13018.745,13020.314333,5274.848500,5276.417833
13,2025/07/22,16:42:58.863080,EncryptionHandler - handleReceivePublicKey,1.570916ms,Client2,1.570916,13021.210,13022.780916,5276.417833,5277.988749
14,2025/07/22,16:42:58.881874,HEService - PartialRelinKeyAggregation,2.422792ms,Client1,2.422792,13040.004,13042.426792,5277.988749,5280.411541
15,2025/07/22,16:42:59.063884,HEService - PartialRelinKeyAggregation,2.646667ms,Client2,2.646667,13222.014,13224.660667,5280.411541,5283.058208
16,2025/07/22,16:42:59.221070,startEncryptionSetupPhaseFor,5.37431925s,AggregationService,5374.319250,13379.200,18753.519250,5283.058208,10657.377458

In [11]:
df = px.data.tips()
fig = px.bar(initializiation_data, base="StartMs", x="runtime_ms", y="Service", color='Name', orientation='h',
             hover_data=["EndTime", "StartMs", "runtime_ms"], labels={"runtime_ms": "Runtime in millisecond", "Service": "Service"}, color_discrete_sequence=px.colors.qualitative.Safe,
             height=400)
fig.show()

In [12]:
request_client_training = data_joined.loc[data_joined["Name"] == "requestClientTraining"].index

print(request_client_training[0])
print(request_client_training[1])

data_after_upload = data_joined[request_client_training[0]:request_client_training[1]]
data_after_upload

17
31

,Date,EndTime,Name,Runtime,Service,runtime_ms,StartMs,EndMs,Start_without_offset,End_without_offset
17,2025/07/22,16:43:09.286822,requestClientTraining,4.1685ms,AggregationService,4.168500,23444.952,23449.120500,10657.377458,10661.545958
18,2025/07/22,16:43:22.080275,HEService - Encrypt,877.91425ms,Client2,877.914250,36238.405,37116.319250,10661.545958,11539.460208
19,2025/07/22,16:43:22.128913,HEService - Encrypt,881.40125ms,Client1,881.401250,36287.043,37168.444250,11539.460208,12420.861458
20,2025/07/22,16:43:23.387515,DataSpaceClientService - UploadData,1.260182542s,Client2,1260.182542,37545.645,38805.827542,12420.861458,13681.044000
21,2025/07/22,16:43:23.424320,DataSpaceClientService - UploadData,1.249576167s,Client1,1249.576167,37582.450,38832.026167,13681.044000,14930.620167
22,2025/07/22,16:43:25.141169,aggregateWeights,56.834709ms,AggregationService,56.834709,39299.299,39356.133709,14930.620167,14987.454876
23,2025/07/22,16:43:25.337108,HEService - PublicKeySwitchGeneration,30.754458ms,Client1,30.754458,39495.238,39525.992458,14987.454876,15018.209334
24,2025/07/22,16:43:25.337140,EncryptionHandler - handlePublicKeySwitch,107.125417ms,Client1,107.125417,39495.270,39602.395417,15018.209334,15125.334751
25,2025/07/22,16:43:25.538703,HEService - PublicKeySwitchGeneration,30.010208ms,Client2,30.010208,39696.833,39726.843208,15125.334751,15155.344959
26,2025/07/22,16:43:25.538735,EncryptionHandler - handlePublicKeySwitch,106.422542ms,Client2,106.422542,39696.865,39803.287542,15155.344959,15261.767501
27,2025/07/22,16:43:25.538867,initiateKeySwitchGeneration,397.6255ms,AggregationService,397.625500,39696.997,40094.622500,15261.767501,15659.393001
28,2025/07/22,16:43:25.539497,EncryptionHandler - handlePublicKeySwitchAggre...,7.333µs,Client1,0.007333,39697.627,39697.634333,15659.393001,15659.400334
29,2025/07/22,16:43:25.540009,EncryptionHandler - handlePublicKeySwitchAggre...,13.166µs,Client2,0.013166,39698.139,39698.152166,15659.400334,15659.413500
30,2025/07/22,16:43:28.692864,updateClientModels,2.229893459s,AggregationService,2229.893459,42850.994,45080.887459,15659.413500,17889.306959

In [20]:
df = px.data.tips()
fig = px.bar(data_after_upload, base="StartMs", x="runtime_ms", y="Service", color='Name', orientation='h',
             hover_data=["EndTime", "StartMs", "runtime_ms"], labels={"runtime_ms": "Runtime in millisecond", "Service": "Service"}, color_discrete_sequence=px.colors.qualitative.Safe,
             height=400)

max_box = data_after_upload.iloc[1]["StartMs"]-300
min_box = data_after_upload.iloc[0]["EndMs"]+300
fig.add_shape(
    type="rect",
    x0=min_box,  # Start x position
    y0=-0.4,  # Start y position (below the bars)
    x1=max_box,   # End x position
    y1=2.4,  # End y position
    fillcolor="lightblue",  # Pastel blue color
    opacity=0.6,
    line=dict(color="lightblue", width=1),
)
fig.add_annotation(
    x=min_box + (max_box-min_box)/2,  # Center of the rectangle
    y=(2.4-0.4)/2+0.1,  # Position above the rectangle
    text="Training Phase of the two python ml clients",
    showarrow=False,
    font=dict(size=12, color="black"),
    opacity=0.8
)

fig.show()